= Dreamer
:author: Overcast Warmth System
:license-url: https://creativecommons.org/licenses/by-nc/4.0/
:license-title: CC BY-NC 4.0
:docinfo: shared
:reproducible:

"One could compare memories to photographs. If you focus on something for long enough, you can burn it into your mind, much like how a polaroid camera can resolve an incredibly detailed photograph given enough exposure and patience. This belief is rather thin, on the basis that the mind is something of which we are still yet to understand, even with all of our research into it. It's remarkable that we were able to prototype memory extraction, let alone store them on data pearl, with how much is still unknown of the world."
-- Fleeting Memories in Mind

---

The Dreamer wakes up.

Actually, calling it _waking up_ is a... bit misleading. They don't particularly understand the difference between being asleep and being awake. Sometimes they are, sometimes they aren't. It's strange, but they're used to it.

They scan the fuzzy area around them, the corners of their vision fuzzy and incoherent. Everything looks particularly fuzzy, but some parts are coherent enough to identify.

The surroundings are unmistakably ancient-made. The horizon resembles shape of smokestacks and factories, and a suspended bridge leading to a spire of walkways and triangular roofs. The Dreamer recognises that as the towering citadel, with the bridge connecting it to the sprawling factories below. This must mean that they're somewhere near the transmission mast?

They look behind and up, and they see the towering mast behind them. So that _is_ correct. They turn and sit down, focusing on the ground beneath them. It's warm, the feeling of wet metal underneath them, sunlight glinting in the small puddles left over. This dream is remarkably coherent!
They wonder if... yes, there they are! They can see a pack of vultures converging in the air, before flying in their own directions. The Dreamer moves forward to dangle their legs off the side of the platform and peer down at the ground below them. The mast's thick supporting wires converge just below them. Under that, further platforms and eventually a large network of significantly smaller, but still fairly large communication equipment.
Few creatures would dare come this far up the mast, so it's a very peaceful place.

The Dreamer sits atop the tower, staring into the sunset as the clouds begin to grow darker. They eventually doze off. But just before the first drops of bullet rain bombard the earth below, something, some__one__ grabs them by the tail and begins franticly dragging them towards a pipe. The Dreamer gets up and prepares to growl in protest, but when they turn around...

There's nobody there. +
They're... alone. +
...

---

xref:../readme#[Home] ~ xref:../chapters#[Chapters] ~ Next
